# Generated by Django 5.2.17 on 2026-08-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
